### ISSUE TITLE
Weird Inconsistent line height using Cobalt2 Theme.

### ISSUE THREAD

**Issue by sdempsey** [wesbos/cobalt2-atom#14] opened 2017-06-21 15:05 UTC
That subject sucks and I know it but I'm not sure of a better way to describe the issue.  A little background.  Wrote a Less mixin today and was annotating it when i noticed some weird inconsistent line height on lines 6 and 7:

![screen shot 2017-06-21 at 11 03 53 am](https://user-images.githubusercontent.com/5795146/27391212-5a490eb6-5671-11e7-8dc9-eb888aaf21c4.png)

Using Source Code Pro for Powerline.  First time I've noticed this issue.  Looks fine in other .less files, javascript, etc...

I was going to see if the Atom devs knew what was going on here but before i fired off a tweet at them i decided to try switching themes/fonts.  Didn't even need to switch fonts.  Switching to Atom Dark fixes the spacing issue.   

![screen shot 2017-06-21 at 11 03 23 am](https://user-images.githubusercontent.com/5795146/27391186-449185bc-5671-11e7-8954-435f7d268117.png)

Any idea what's going on here?  It's not as though the editor has become unusable i'm just a picky nerd. 🤓

**Comment by rosston** [comment] 2017-06-21 16:57
🤔  You've certainly found an interesting bug! I've tried replicating with a few combinations of these options:
* font (tried both Source Code Pro and Source Code Pro for Powerline)
* font size (just used the default 14px)
* line height (tried both 1.4 and the default 1.5)

I'm using the exact same text and the exact same text spacing as you are and still can't replicate. FWIW, I'm on macOS 10.12.5 (because who knows what's causing this bug now).

I'm willing to take some more detail about your config (e.g., font size and if you're using a non-default language package for LESS) and try to replicate. But unfortunately, I might have to rely on you to figure out the cause. You can launch the Chromium dev tools from in Atom using ctrl + alt + i (or cmd + alt + i on macOS) and use those to check out the CSS like you would on a regular website. Let me know if/what you find!

**Comment by sdempsey** [comment] 2017-06-21 17:50
So Inspecting the panel where i'm seeing the error provides some interesting albeit still confusing insight.  In terms of the editors DOM it looks like row's 1-6 are rendered in one absolutely positioned container and 7-12 in another.  Both positioned using some inline transforms.  I suspect there is some sub-pixel rendering error happening here but manipulating the values doesn't seem to have any effect (e.g. I manipulate the transform values in the inspector and nothing appears to change. hitting enter to confirm the change resets the values).  I was however able to uncheck the transform on the container for rows 7-12 and watch it disappear from the editor.  

![screen shot 2017-06-21 at 1 43 35 pm](https://user-images.githubusercontent.com/5795146/27398431-b96a380a-5687-11e7-8943-fd527266705d.png)
![screen shot 2017-06-21 at 1 43 57 pm](https://user-images.githubusercontent.com/5795146/27398439-bd303458-5687-11e7-8237-98069019d6f2.png)

Even stranger when opening the inspector it was docked to the right which was squishing the pane quite a bit and the line-height issue seemed to disappear.  

![screen shot 2017-06-21 at 1 49 41 pm](https://user-images.githubusercontent.com/5795146/27398686-8aa07b50-5688-11e7-85af-0705f8889bd1.png)


¯\_(ツ)_/¯


If your feeling curious enough to keep digging I'm happy to keep working on it but I'm not sure its the Syntax theme's fault anymore.

**Comment by rosston** [comment] 2017-07-09 21:56
@sdempsey OK, I looked at this again given the digging that you did. I was able to see the same 2 types of positioned/transformed divs in my editor (albeit, still without replicating your issue). I'm pretty sure those 2 divs are tiles, [which Atom uses for rendering groups of lines](http://blog.atom.io/2015/06/24/rendering-improvements.html#tiles-to-the-rescue).

My wild guess would be that the math was wrong on the 1st and/or 2nd tiles in your case. But that would definitely be an editor issue. So I'll close this issue. Hopefully you don't run into this problem a bunch more.

**Closed as completed by rosston** 2017-07-09 21:56 UTC
